# Port de l'application (commun à tous)
quarkus.http.port=8081

quarkus.console.color=true
quarkus.log.console.format=%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c{3.}] (%t) %s%e%n

quarkus.hibernate-orm.schema-management.strategy=drop-and-create
%dev.quarkus.hibernate-orm.dev-ui.allow-hql=true

# Configuration du connecteur Kafka pour le canal entrant
mp.messaging.incoming.utilisateurs-events.connector=smallrye-kafka
mp.messaging.incoming.utilisateurs-events.topic=utilisateurs-events

# Configuration pour le mode DEV local
%dev.quarkus.datasource.db-kind=h2
%dev.quarkus.datasource.username=sa
%dev.quarkus.datasource.password=sa
%dev.quarkus.datasource.jdbc.url=jdbc:h2:mem:schpapps-genealogie-db

# Configuration par défaut pour "mvn test" (Profil %test)
%test.quarkus.datasource.db-kind=h2
%test.quarkus.datasource.username=sa
%test.quarkus.datasource.password=sa
%test.quarkus.datasource.jdbc.url=jdbc:h2:mem:schpapps-genealogie-db

# Configuration pour tes tests d'intégration (Profil %it)
%it.quarkus.datasource.db-kind=postgresql
%it.quarkus.datasource.devservices.image-name=postgres:alpine

# Configuration pour le PACKAGING / PRODUCTION
%prod.quarkus.datasource.db-kind=h2
%prod.quarkus.datasource.username=sa
%prod.quarkus.datasource.password=sa
%prod.quarkus.datasource.jdbc.url=jdbc:h2:mem:schpapps-genealogie-db