FROM eclipse-temurin:25-jre

ENV LANGUAGE='fr_FR:fr'
ENV LC_ALL='fr_FR.UTF-8'

WORKDIR /work/

# Configuration d'un utilisateur non-root pour la sécurité
RUN useradd -u 1001 quarkus && chown -R 1001 /work
USER 1001

# Copie de l'arborescence fast-jar générée par Quarkus
COPY --chown=1001:1001 target/quarkus-app/lib/ /work/lib/
COPY --chown=1001:1001 target/quarkus-app/*.jar /work/
COPY --chown=1001:1001 target/quarkus-app/app/ /work/app/
COPY --chown=1001:1001 target/quarkus-app/quarkus/ /work/quarkus/

EXPOSE 8080

ENTRYPOINT ["java", \
  "-Dquarkus.http.host=0.0.0.0", \
  "-Djava.util.logging.manager=org.jboss.logmanager.LogManager", \
  "-jar", \
  "/work/quarkus-run.jar"]