name: Java CI & Quality

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # Job 1 : Exécuté uniquement lors d'un PUSH (Tests Unitaires uniquement)
  unit-tests-on-push:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run Unit Tests
        run: mvn -B clean test

  # Job 2 : Exécuté uniquement lors d'une PR vers main (TU + TI + SonarQube)
  pr-validation:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Requis par Sonar pour le blame Git et l'analyse de code

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run All Tests (TU + TI) and SonarQube Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn -B clean verify sonar:sonar \
            -Dsonar.projectKey=schpapps-genealogie
