# Job exécuté lors d'une PR vers main (lance tous les tests et le scan Sonar)
name: Pull Request Validation (TU + TI + SonarQube)

on:
  pull_request:
    branches: [ "main" ]

jobs:
  pr-validation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0  # Requis par Sonar pour le blame Git et l'analyse de code

      - name: Set up JDK 25
        uses: actions/setup-java@v6
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run All Tests (TU + TI) and SonarQube Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn -B clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.organization=jecash666 \
            -Dsonar.projectKey=schpapps-genealogie
