# Job exécuté lors d'une PR vers main (lance tous les tests et le scan Sonar)
name: Pull Request Validation

on:
  pull_request:
    branches: [ "main" ]

jobs:
  pr-validation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        # 7.0.1
        with:
          fetch-depth: 0  # Requis par Sonar pour le blame Git et l'analyse de code

      - name: Set up JDK 25
        uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c
        # 6.0.0
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run All Tests (TU + TI) and SonarQube Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn -B clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.organization=jecash666 \
            -Dsonar.projectKey=Fiegel_schpapps-genealogie \
            -Dsonar.coverage.jacoco.xmlReportPaths=target/jacoco-report/jacoco.xml
